blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/PGPWdRBQms
    about: Feel free to ask your questions here. Reporting bugs here is also possible, i might be quicker to see them there
